/**
 * Seed script: populates the protocols table with a representative set of DeFi protocols.
 * Idempotent — uses ON CONFLICT DO NOTHING so it is safe to re-run.
 *
 * Usage:  npm run db:seed
 */

import { Pool, neonConfig } from '@neondatabase/serverless';
import { drizzle } from 'drizzle-orm/neon-serverless';
import { sql } from 'drizzle-orm';
import ws from 'ws';
import * as schema from '../../shared/schema.js';

neonConfig.webSocketConstructor = ws;

if (!process.env.DATABASE_URL) {
  throw new Error('DATABASE_URL must be set. Did you forget to provision a database?');
}

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const db = drizzle({ client: pool, schema });

const seedProtocols: typeof schema.protocols.$inferInsert[] = [
  {
    id: 'uniswap',
    name: 'Uniswap',
    chains: ['Ethereum', 'Polygon', 'Arbitrum', 'Optimism', 'Base'],
    category: 'DEX',
    tvl: 4_800_000_000,
    volume24h: 1_200_000_000,
    change24h: 2.4,
    age: 2100,
    audited: true,
    auditCount: 5,
    auditNote: 'Audited by Trail of Bits, ABDK, and others',
    auditLinks: ['https://github.com/Uniswap/v3-core/tree/main/audits'],
    securityScore: 91,
    logo: 'https://cryptologos.cc/logos/uniswap-uni-logo.png',
    website: 'https://uniswap.org',
    twitter: 'https://twitter.com/Uniswap',
    github: 'https://github.com/Uniswap',
    description:
      'Uniswap is the leading decentralized exchange (DEX) protocol built on Ethereum. It uses an automated market maker (AMM) model allowing users to swap ERC-20 tokens without an order book.',
    manuallyAdded: true,
    defiHasMultisig: true,
    defiHasTimelock: true,
  },
  {
    id: 'aave',
    name: 'Aave',
    chains: ['Ethereum', 'Polygon', 'Avalanche', 'Arbitrum', 'Optimism'],
    category: 'Lending',
    tvl: 12_500_000_000,
    volume24h: 320_000_000,
    change24h: 1.1,
    age: 1800,
    audited: true,
    auditCount: 7,
    auditNote: 'Audited by OpenZeppelin, Trail of Bits, and CertiK',
    auditLinks: ['https://docs.aave.com/developers/deployed-contracts/security-and-audits'],
    securityScore: 94,
    logo: 'https://cryptologos.cc/logos/aave-aave-logo.png',
    website: 'https://aave.com',
    twitter: 'https://twitter.com/aaveaave',
    github: 'https://github.com/aave',
    description:
      'Aave is an open-source, non-custodial liquidity protocol where users can earn interest on deposits and borrow assets. It pioneered flash loans and supports a wide range of assets.',
    manuallyAdded: true,
    defiHasMultisig: true,
    defiHasTimelock: true,
  },
  {
    id: 'compound',
    name: 'Compound',
    chains: ['Ethereum'],
    category: 'Lending',
    tvl: 2_100_000_000,
    volume24h: 85_000_000,
    change24h: -0.7,
    age: 2200,
    audited: true,
    auditCount: 4,
    auditNote: 'Audited by Trail of Bits and OpenZeppelin',
    auditLinks: ['https://compound.finance/docs/security'],
    securityScore: 89,
    logo: 'https://cryptologos.cc/logos/compound-comp-logo.png',
    website: 'https://compound.finance',
    twitter: 'https://twitter.com/compoundfinance',
    github: 'https://github.com/compound-finance',
    description:
      'Compound is an algorithmic, autonomous interest rate protocol built for developers to unlock a universe of open financial applications. Users supply assets to earn interest and borrow against collateral.',
    manuallyAdded: true,
    defiHasMultisig: true,
    defiHasTimelock: true,
  },
  {
    id: 'makerdao',
    name: 'MakerDAO',
    chains: ['Ethereum'],
    category: 'Stablecoin',
    tvl: 8_900_000_000,
    volume24h: 210_000_000,
    change24h: 0.3,
    age: 2700,
    audited: true,
    auditCount: 6,
    auditNote: 'Audited by Trail of Bits, Peckshield, and others',
    auditLinks: ['https://security.makerdao.com'],
    securityScore: 93,
    logo: 'https://cryptologos.cc/logos/maker-mkr-logo.png',
    website: 'https://makerdao.com',
    twitter: 'https://twitter.com/MakerDAO',
    github: 'https://github.com/makerdao',
    description:
      'MakerDAO is the decentralized organization behind the DAI stablecoin. Users lock collateral to mint DAI, a soft-pegged USD stablecoin, enabling decentralized borrowing without centralized intermediaries.',
    manuallyAdded: true,
    defiHasMultisig: true,
    defiHasTimelock: true,
  },
  {
    id: 'curve',
    name: 'Curve Finance',
    chains: ['Ethereum', 'Polygon', 'Arbitrum', 'Avalanche', 'Fantom'],
    category: 'DEX',
    tvl: 3_600_000_000,
    volume24h: 450_000_000,
    change24h: 1.8,
    age: 1900,
    audited: true,
    auditCount: 3,
    auditNote: 'Audited by Trail of Bits and Quantstamp',
    auditLinks: ['https://curve.readthedocs.io/security-audits.html'],
    securityScore: 87,
    logo: 'https://cryptologos.cc/logos/curve-dao-token-crv-logo.png',
    website: 'https://curve.fi',
    twitter: 'https://twitter.com/CurveFinance',
    github: 'https://github.com/curvefi',
    description:
      'Curve Finance is an automated market maker (AMM) optimized for low-slippage swaps between stablecoins and similarly priced assets, using a specialized bonding curve formula.',
    manuallyAdded: true,
    defiHasMultisig: false,
    defiHasTimelock: true,
  },
  {
    id: 'lido',
    name: 'Lido',
    chains: ['Ethereum', 'Polygon', 'Solana'],
    category: 'Liquid Staking',
    tvl: 29_000_000_000,
    volume24h: 180_000_000,
    change24h: 2.9,
    age: 1400,
    audited: true,
    auditCount: 8,
    auditNote: 'Audited by Sigma Prime, MixBytes, and others',
    auditLinks: ['https://github.com/lidofinance/audits'],
    securityScore: 90,
    logo: 'https://cryptologos.cc/logos/lido-dao-ldo-logo.png',
    website: 'https://lido.fi',
    twitter: 'https://twitter.com/LidoFinance',
    github: 'https://github.com/lidofinance',
    description:
      'Lido is a liquid staking solution for Ethereum (and other PoS chains) that lets users stake ETH and receive stETH in return, enabling staking rewards while keeping assets liquid.',
    manuallyAdded: true,
    defiHasMultisig: true,
    defiHasTimelock: true,
  },
  {
    id: 'pancakeswap',
    name: 'PancakeSwap',
    chains: ['BNB Chain', 'Ethereum', 'Arbitrum', 'Base'],
    category: 'DEX',
    tvl: 1_800_000_000,
    volume24h: 380_000_000,
    change24h: 3.1,
    age: 1600,
    audited: true,
    auditCount: 3,
    auditNote: 'Audited by CertiK and PeckShield',
    auditLinks: ['https://docs.pancakeswap.finance/readme/audits'],
    securityScore: 82,
    logo: 'https://cryptologos.cc/logos/pancakeswap-cake-logo.png',
    website: 'https://pancakeswap.finance',
    twitter: 'https://twitter.com/PancakeSwap',
    github: 'https://github.com/pancakeswap',
    description:
      'PancakeSwap is the leading DEX on BNB Chain, offering token swaps, yield farming, syrup pools, and lotteries. It uses the AMM model and has expanded to multiple chains.',
    manuallyAdded: true,
    defiHasMultisig: true,
    defiHasTimelock: false,
  },
  {
    id: 'convex-finance',
    name: 'Convex Finance',
    chains: ['Ethereum'],
    category: 'Yield',
    tvl: 2_400_000_000,
    volume24h: 55_000_000,
    change24h: -1.2,
    age: 1100,
    audited: true,
    auditCount: 2,
    auditNote: 'Audited by MixBytes and Arbitrary Execution',
    auditLinks: ['https://github.com/convex-eth/platform/tree/main/audits'],
    securityScore: 84,
    logo: 'https://cryptologos.cc/logos/convex-finance-cvx-logo.png',
    website: 'https://convexfinance.com',
    twitter: 'https://twitter.com/ConvexFinance',
    github: 'https://github.com/convex-eth',
    description:
      'Convex Finance simplifies Curve Finance staking and liquidity provision. CRV stakers and liquidity providers earn enhanced rewards without locking tokens directly in Curve.',
    manuallyAdded: true,
    defiHasMultisig: true,
    defiHasTimelock: false,
  },
  {
    id: 'gmx',
    name: 'GMX',
    chains: ['Arbitrum', 'Avalanche'],
    category: 'Derivatives',
    tvl: 950_000_000,
    volume24h: 420_000_000,
    change24h: 4.2,
    age: 1000,
    audited: true,
    auditCount: 2,
    auditNote: 'Audited by ABDK and Code4rena community',
    auditLinks: ['https://gmx.io/#/security'],
    securityScore: 85,
    logo: 'https://cryptologos.cc/logos/gmx-gmx-logo.png',
    website: 'https://gmx.io',
    twitter: 'https://twitter.com/GMX_IO',
    github: 'https://github.com/gmx-io',
    description:
      'GMX is a decentralized spot and perpetual exchange on Arbitrum and Avalanche that allows leverage trading up to 50x with low fees and zero price impact swaps using a multi-asset pool.',
    manuallyAdded: true,
    defiHasMultisig: true,
    defiHasTimelock: false,
  },
  {
    id: 'yearn-finance',
    name: 'Yearn Finance',
    chains: ['Ethereum', 'Fantom', 'Arbitrum'],
    category: 'Yield',
    tvl: 580_000_000,
    volume24h: 28_000_000,
    change24h: 0.6,
    age: 1850,
    audited: true,
    auditCount: 4,
    auditNote: 'Audited by Trail of Bits, MixBytes, and Chainsecurity',
    auditLinks: ['https://docs.yearn.finance/security/audits'],
    securityScore: 88,
    logo: 'https://cryptologos.cc/logos/yearn-finance-yfi-logo.png',
    website: 'https://yearn.finance',
    twitter: 'https://twitter.com/yearnfinance',
    github: 'https://github.com/yearn',
    description:
      'Yearn Finance is a suite of DeFi products that provide yield generation, lending aggregation, and more. Its flagship product, Vaults, auto-compounds yields on deposited assets.',
    manuallyAdded: true,
    defiHasMultisig: true,
    defiHasTimelock: true,
  },
  {
    id: 'balancer',
    name: 'Balancer',
    chains: ['Ethereum', 'Polygon', 'Arbitrum', 'Optimism'],
    category: 'DEX',
    tvl: 1_150_000_000,
    volume24h: 95_000_000,
    change24h: -0.4,
    age: 1700,
    audited: true,
    auditCount: 4,
    auditNote: 'Audited by Trail of Bits and OpenZeppelin',
    auditLinks: ['https://docs.balancer.fi/concepts/security/audits.html'],
    securityScore: 86,
    logo: 'https://cryptologos.cc/logos/balancer-bal-logo.png',
    website: 'https://balancer.fi',
    twitter: 'https://twitter.com/Balancer',
    github: 'https://github.com/balancer',
    description:
      'Balancer is an automated portfolio manager and DEX that allows users to create and manage liquidity pools with up to 8 tokens at custom weights, earning trading fees in the process.',
    manuallyAdded: true,
    defiHasMultisig: true,
    defiHasTimelock: true,
  },
  {
    id: 'rocket-pool',
    name: 'Rocket Pool',
    chains: ['Ethereum'],
    category: 'Liquid Staking',
    tvl: 3_800_000_000,
    volume24h: 42_000_000,
    change24h: 1.5,
    age: 900,
    audited: true,
    auditCount: 5,
    auditNote: 'Audited by Sigma Prime, ConsenSys Diligence, and others',
    auditLinks: ['https://rocketpool.net/security'],
    securityScore: 92,
    logo: 'https://cryptologos.cc/logos/rocket-pool-rpl-logo.png',
    website: 'https://rocketpool.net',
    twitter: 'https://twitter.com/Rocket_Pool',
    github: 'https://github.com/rocket-pool',
    description:
      'Rocket Pool is a decentralized Ethereum staking protocol. Users can stake as little as 0.01 ETH and receive rETH tokens, while node operators can run validators with only 8 ETH.',
    manuallyAdded: true,
    defiHasMultisig: true,
    defiHasTimelock: true,
  },
  {
    id: 'sushiswap',
    name: 'SushiSwap',
    chains: ['Ethereum', 'Polygon', 'BNB Chain', 'Arbitrum', 'Avalanche'],
    category: 'DEX',
    tvl: 420_000_000,
    volume24h: 75_000_000,
    change24h: -2.1,
    age: 1650,
    audited: true,
    auditCount: 3,
    auditNote: 'Audited by PeckShield and Quantstamp',
    auditLinks: ['https://docs.sushi.com/products/security'],
    securityScore: 78,
    logo: 'https://cryptologos.cc/logos/sushiswap-sushi-logo.png',
    website: 'https://sushi.com',
    twitter: 'https://twitter.com/SushiSwap',
    github: 'https://github.com/sushiswap',
    description:
      'SushiSwap is a community-driven DEX and DeFi ecosystem offering token swaps, concentrated liquidity, lending, and cross-chain operations across 25+ blockchain networks.',
    manuallyAdded: true,
    defiHasMultisig: true,
    defiHasTimelock: false,
  },
  {
    id: 'synthetix',
    name: 'Synthetix',
    chains: ['Ethereum', 'Optimism'],
    category: 'Derivatives',
    tvl: 680_000_000,
    volume24h: 160_000_000,
    change24h: 0.9,
    age: 2300,
    audited: true,
    auditCount: 4,
    auditNote: 'Audited by Iosiro and Sigma Prime',
    auditLinks: ['https://docs.synthetix.io/dao/security'],
    securityScore: 83,
    logo: 'https://cryptologos.cc/logos/synthetix-network-token-snx-logo.png',
    website: 'https://synthetix.io',
    twitter: 'https://twitter.com/synthetix_io',
    github: 'https://github.com/Synthetixio',
    description:
      'Synthetix is a decentralized liquidity provision protocol enabling the creation of synthetic assets (Synths) that track real-world prices, powering derivatives and perp trading on Optimism.',
    manuallyAdded: true,
    defiHasMultisig: true,
    defiHasTimelock: true,
  },
  {
    id: 'pendle',
    name: 'Pendle',
    chains: ['Ethereum', 'Arbitrum', 'BNB Chain'],
    category: 'Yield',
    tvl: 3_200_000_000,
    volume24h: 95_000_000,
    change24h: 5.3,
    age: 700,
    audited: true,
    auditCount: 3,
    auditNote: 'Audited by Ackee Blockchain and Spearbit',
    auditLinks: ['https://github.com/pendle-finance/pendle-core-v2-public/tree/main/audits'],
    securityScore: 86,
    logo: 'https://cryptologos.cc/logos/pendle-pendle-logo.png',
    website: 'https://pendle.finance',
    twitter: 'https://twitter.com/pendle_fi',
    github: 'https://github.com/pendle-finance',
    description:
      'Pendle is a yield trading protocol that allows users to tokenize and sell future yield. It separates yield-bearing assets into principal and yield tokens, enabling fixed-rate strategies and yield speculation.',
    manuallyAdded: true,
    defiHasMultisig: true,
    defiHasTimelock: false,
  },
];

async function seed() {
  console.log(`Seeding ${seedProtocols.length} protocols...`);

  for (const protocol of seedProtocols) {
    await db
      .insert(schema.protocols)
      .values(protocol as any)
      .onConflictDoNothing({ target: schema.protocols.id });
  }

  // Verify
  const count = await db.execute(sql`SELECT COUNT(*) FROM protocols`);
  const total = Number((count.rows[0] as any).count);
  console.log(`✅ Done. protocols table now has ${total} row(s).`);

  await pool.end();
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
